# Generated by Django 2.1 on 2018-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0005_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to='cover_images/'),
        ),
    ]
