# Generated by Django 2.1 on 2018-10-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0007_auto_20181016_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
