# Generated by Django 2.1 on 2018-10-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0008_auto_20181016_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='mainblog.Tag'),
        ),
    ]
