# Generated by Django 2.1 on 2018-10-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0009_auto_20181016_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to='cover_images/'),
        ),
    ]
