# Generated by Django 2.1 on 2018-10-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0013_auto_20181019_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_input',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
